# ---------------------------------------------------------------------------
# OIDC Auth Systems
# ---------------------------------------------------------------------------
# See `docs/config/oidc_providers.md`) for a full example and semantics.
# ---------------------------------------------------------------------------
oidc_client_pem_path: "./cacert.pem"

auth_systems:

  - id: "keycloak"
    title: "Authenticate with Keycloak"
    server_url: "https://sso.domain.net/realms/soliplex"
    client_id: "soliplex-service"
    client_secret: ""  # "secret:{SOLIPLEX_CLIENT_SECRET}"
    scope: "openid email profile"
    token_validation_pem: |
        -----BEGIN PUBLIC KEY-----
        MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAutt7XlnN7OtFx7p6WMif
        SlUYMQ62RO/7x5hwWsvYhdHejd9KDBP8EZxIWk3vsMD0JhVl2cMNwMEqyU0CqHrS
        E13+79lpG9trpfM674JyE9LwuGYX0YCkwtWA5zwlXjbHObr7WgziDP4+Nfs/1mtv
        qERlvChBX6pyz/bgFtA9a0eZlXZbXSP5XwiHtHhMTil4MWBihLiN7nU7r0goduyf
        eB7WiOJQ/p6kl/Y+FKdnVt8KHAudA2iErJ8mlPKaWLob5MipNsCB7WVTn16qq/O/
        PYiyk134+YXSMfWM8GxRb8/WtfwYlkaXXCB1YAj5M0O3RJLhTEvXMo2KUilOhKXX
        DQIDAQAB
        -----END PUBLIC KEY-----
